"""Add created_at to Channel model

Revision ID: 218b12fe8022
Revises: 34b3d39281f3
Create Date: 2025-11-13 17:46:39.408547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218b12fe8022'
down_revision: Union[str, Sequence[str], None] = '34b3d39281f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'created_at')
    # ### end Alembic commands ###
